version: "3.7"
services:
  flink-jobmanager:
    image: flink:latest
    command: jobmanager
    ports:
      - 7001:8081
    volumes:
      - type: bind
        source: ./flink-conf.yaml
        target: /opt/flink/conf/flink-conf.yaml
  flink-taskmanager:
    image: flink:latest
    depends_on:
      - flink-jobmanager
    command: taskmanager
    ports:
      - "7002-7100:3000"
    volumes:
      - type: bind
        source: ./flink-conf.yaml
        target: /opt/flink/conf/flink-conf.yaml
    links:
      - flink-jobmanager

networks:
  default:
    external:
      name: stream-processing-playground
